

package shopping;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Add extends javax.swing.JFrame {

    /** Creates new form backstore */
    public Add() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfname = new javax.swing.JTextField();
        tfprice = new javax.swing.JTextField();
        tfman = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tadesc = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Product - Shopping Mall System");
        setBounds(new java.awt.Rectangle(137, 80, 0, 0));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tfname.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16));
        tfname.setForeground(new java.awt.Color(0, 102, 102));
        tfname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 20), new java.awt.Color(0, 102, 102))); // NOI18N
        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfname);
        tfname.setBounds(20, 180, 410, 90);

        tfprice.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16));
        tfprice.setForeground(new java.awt.Color(0, 102, 102));
        tfprice.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfprice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Price", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 20), new java.awt.Color(51, 51, 51))); // NOI18N
        getContentPane().add(tfprice);
        tfprice.setBounds(20, 390, 237, 90);

        tfman.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16));
        tfman.setForeground(new java.awt.Color(51, 51, 51));
        tfman.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfman.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manufacturer of the Product", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 20), new java.awt.Color(51, 51, 51))); // NOI18N
        getContentPane().add(tfman);
        tfman.setBounds(20, 280, 410, 90);

        tadesc.setColumns(20);
        tadesc.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16));
        tadesc.setForeground(new java.awt.Color(51, 51, 51));
        tadesc.setLineWrap(true);
        tadesc.setRows(5);
        tadesc.setWrapStyleWord(true);
        tadesc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Description", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 20), new java.awt.Color(51, 51, 51))); // NOI18N
        tadesc.setMinimumSize(new java.awt.Dimension(336, 310));
        tadesc.setPreferredSize(new java.awt.Dimension(336, 310));
        jScrollPane2.setViewportView(tadesc);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(450, 190, 290, 280);

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 20));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(290, 415, 100, 40);

        jButton3.setBackground(new java.awt.Color(120, 0, 0));
        jButton3.setFont(new java.awt.Font("Aharoni", 1, 24));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 510, 270, 60);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Aharoni", 1, 28));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD NEW PRODUCT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 510, 430, 60);

        jLabel1.setText("Select Quantity");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 310, 96, 14);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\logo the mall.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 10, 170, 150);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 30));
        jLabel3.setForeground(new java.awt.Color(11, 198, 160));
        jLabel3.setText("ADD PRODUCTS HERE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 40, 290, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\CLOSE.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(713, 2, 35, 35);

        jLabel9.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\MINIMISE.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(673, 2, 35, 35);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            Class.forName("java.sql.DriverManager");

            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/store", "root", "tiger");

            Statement stmt = (Statement) con.createStatement();


                String name =tfname.getText();
                String man = tfman.getText();
                String desc =tadesc.getText();
                String amt=tfprice.getText();                
                String quan=(String)jComboBox1.getSelectedItem();
                

if(name.isEmpty()==false && man.isEmpty()==false && desc.isEmpty()==false
   && amt.isEmpty()==false && quan.isEmpty()==false)
           {
            int price=Integer.parseInt(amt);
            int qty = Integer.parseInt(quan);

                String querydel="delete from shop where name='"+name+"';";
                String query="insert into shop values('"+name+"','"+man+"'"+",'"+desc+"',"+price+","+qty+");";
                stmt.executeUpdate(querydel);
                stmt.executeUpdate(query);

                JOptionPane.showMessageDialog(this,"Product Added Successfully");
                //jButton5.doClick();
                tfname.setText("");
                tfman.setText("");
                tadesc.setText("");
                tfprice.setText("");
            }
 else
{
                    JOptionPane.showMessageDialog(this,"Fields Empty");
 }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  Menu avail=new Menu();
        avail.setVisible(true);        // TODO add your handling code here:
this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);
}//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(ICONIFIED);
}//GEN-LAST:event_jLabel9MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jLabel9.setIcon(new javax.swing.ImageIcon("D:\\IP PROJECT 2018-19\\PICTURES\\MINIMISE.png"));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\IP PROJECT 2018-19\\PICTURES\\CLOSE.png"));
                 jLabel4.setIcon(new javax.swing.ImageIcon("D:\\IP PROJECT 2018-19\\PICTURES\\logo the mall.png"));        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tadesc;
    private javax.swing.JTextField tfman;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfprice;
    // End of variables declaration//GEN-END:variables

}
