

package shopping;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Delete extends javax.swing.JFrame {

    /** Creates new form backstore */
    public Delete() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tadesc = new javax.swing.JTextArea();
        tfprice = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        tfman = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Product - Shopping Mall System");
        setBounds(new java.awt.Rectangle(127, 5, 0, 0));
        setMinimumSize(new java.awt.Dimension(770, 750));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Aharoni", 1, 24));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 670, 270, 60);

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 20))); // NOI18N
        jList1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16));
        jList1.setForeground(new java.awt.Color(0, 0, 102));
        jList1.setModel(new DefaultListModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 260, 240, 390);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Aharoni", 1, 24));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DELETE PRODUCTS");
        jButton2.setMaximumSize(new java.awt.Dimension(430, 60));
        jButton2.setMinimumSize(new java.awt.Dimension(430, 60));
        jButton2.setPreferredSize(new java.awt.Dimension(430, 60));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 670, 430, 60);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 15));
        jLabel1.setText("Select Quantity:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(590, 410, 110, 15);

        tfname.setEditable(false);
        tfname.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16));
        tfname.setForeground(new java.awt.Color(0, 102, 102));
        tfname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 20), new java.awt.Color(0, 102, 102))); // NOI18N
        getContentPane().add(tfname);
        tfname.setBounds(330, 190, 390, 100);

        tadesc.setColumns(20);
        tadesc.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16));
        tadesc.setForeground(new java.awt.Color(51, 51, 51));
        tadesc.setLineWrap(true);
        tadesc.setRows(5);
        tadesc.setWrapStyleWord(true);
        tadesc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Description", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 20))); // NOI18N
        tadesc.setMinimumSize(new java.awt.Dimension(116, 59));
        jScrollPane2.setViewportView(tadesc);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(330, 510, 380, 140);

        tfprice.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16));
        tfprice.setForeground(new java.awt.Color(0, 102, 102));
        tfprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfprice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 20))); // NOI18N
        getContentPane().add(tfprice);
        tfprice.setBounds(330, 410, 240, 85);

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Aharoni", 1, 24));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SHOW LIST");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(40, 190, 240, 60);

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 20));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(590, 430, 120, 30);

        tfman.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16));
        tfman.setForeground(new java.awt.Color(0, 102, 102));
        tfman.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfman.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manufacturer", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 20))); // NOI18N
        getContentPane().add(tfman);
        tfman.setBounds(330, 300, 390, 100);

        jLabel10.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\CLOSE.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(733, 2, 35, 35);

        jLabel9.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\MINIMISE.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(693, 2, 35, 35);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 30));
        jLabel3.setForeground(new java.awt.Color(11, 198, 160));
        jLabel3.setText("DELETE PRODUCTS ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 80, 420, 50);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\logo the mall.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 30, 150, 150);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 770, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try {

            Class.forName("java.sql.DriverManager");

            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/store", "root", "tiger");

            Statement stmt = (Statement) con.createStatement();


                String name =(String)jList1.getSelectedValue();

if(jList1.isSelectionEmpty()==false)
           {
                String querydel="delete from shop where name='"+name+"';";

                stmt.executeUpdate(querydel);

                JOptionPane.showMessageDialog(this,"Deleted Successfully");
                jButton5.doClick();

            }
 else
{
                    JOptionPane.showMessageDialog(this,"Select the product which you want to delete");
 }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 Menu avail=new Menu();
        avail.setVisible(true);         // TODO add your handling code here:
this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        try {

            Class.forName("java.sql.DriverManager");

            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/store", "root", "tiger");

            Statement stmt = (Statement) con.createStatement();

            String query = "select * from shop where name="+"'"+jList1.getSelectedValue()+"';";


            ResultSet rs = stmt.executeQuery(query);


            while (rs.next()) {

                String name = rs.getString("name");
                String man = rs.getString("man");
                String desc = rs.getString("descp");
                int price= rs.getInt("price");
                int qty = rs.getInt("qty");

                tfman.setText(man);
                tadesc.setText(desc);
                tfprice.setText(""+price);
                jComboBox1.setSelectedIndex(qty-1);
                tfname.setText(name);


            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jList1ValueChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {

            Class.forName("java.sql.DriverManager");

            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/store", "root", "tiger");

            Statement stmt = (Statement) con.createStatement();

            String query = "select name from shop where qty>0;";

            ResultSet rs = stmt.executeQuery(query);

            DefaultListModel dlm = (DefaultListModel) jList1.getModel();

            dlm.removeAllElements();
            while (rs.next()) {

                String name = rs.getString("name");
                dlm.addElement(name);
                jList1.setModel(dlm);


            }

            jList1.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);
}//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(ICONIFIED);
}//GEN-LAST:event_jLabel9MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jLabel9.setIcon(new javax.swing.ImageIcon("D:\\IP PROJECT 2018-19\\PICTURES\\MINIMISE.png"));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\IP PROJECT 2018-19\\PICTURES\\CLOSE.png"));
                 jLabel5.setIcon(new javax.swing.ImageIcon("D:\\IP PROJECT 2018-19\\PICTURES\\logo the mall.png"));        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tadesc;
    private javax.swing.JTextField tfman;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfprice;
    // End of variables declaration//GEN-END:variables

}
