

package shopping;

import java.sql.*;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    Connection con;
    Statement stemt,smt1;
    ResultSet rs;
    java.util.Date dt1;
    /** Creates new form backstore */
    public Login() {
        initComponents();
        try
        {
            Class .forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/store","root","tiger");
        }
        catch(Exception e)
        {
         System.out.println(e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        invalid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idtf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PassWordPF = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Shopping Mall System");
        setBounds(new java.awt.Rectangle(260, 150, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 460));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(11, 198, 160));
        jButton1.setFont(new java.awt.Font("Aharoni", 1, 24));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 360, 380, 50);

        invalid.setFont(new java.awt.Font("Calibri", 0, 16));
        invalid.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(invalid);
        invalid.setBounds(70, 310, 390, 22);

        jLabel2.setBackground(new java.awt.Color(11, 198, 160));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 20));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOG IN");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 198, 160), 1, true));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 360, 380, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\MINIMISE.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(422, 2, 35, 35);

        jLabel6.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\CLOSE.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(462, 2, 35, 35);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 40));
        jLabel3.setForeground(new java.awt.Color(11, 198, 160));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOG IN !");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 60, 140, 40);

        idtf.setFont(new java.awt.Font("Tahoma", 0, 15));
        idtf.setForeground(new java.awt.Color(102, 102, 102));
        idtf.setText("USERNAME");
        idtf.setBorder(null);
        idtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtfActionPerformed(evt);
            }
        });
        idtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idtfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idtfFocusLost(evt);
            }
        });
        getContentPane().add(idtf);
        idtf.setBounds(100, 180, 360, 30);

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 210, 380, 2);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 15));
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 160, 200, 20);

        PassWordPF.setFont(new java.awt.Font("Tahoma", 0, 15));
        PassWordPF.setForeground(new java.awt.Color(102, 102, 102));
        PassWordPF.setText("PASSWORD");
        PassWordPF.setBorder(null);
        PassWordPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassWordPFActionPerformed(evt);
            }
        });
        PassWordPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassWordPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PassWordPFFocusLost(evt);
            }
        });
        getContentPane().add(PassWordPF);
        PassWordPF.setBounds(100, 260, 320, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 15));
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(80, 240, 200, 20);

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 290, 380, 2);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\SHOW PASSWORD.png")); // NOI18N
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(420, 250, 40, 40);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\HIDE PASSWORD.png")); // NOI18N
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(420, 250, 40, 40);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 16));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>  Don't have an account ?  <font color = rgb(11,198,160)> <b>SIGN UP </b></font><font color = rgb(0,0,0)> here </font> </html>");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 430, 290, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 500, 460);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-500)/2, (screenSize.height-460)/2, 500, 460);
    }// </editor-fold>//GEN-END:initComponents
Connection conn = null;
ResultSet rs1 = null;
Statement stmt = null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        invalid.setText("");
        String PWord = new String(PassWordPF.getPassword());
        String ID = idtf.getText();
        String str = null;
        int icon = 0;
        Statement stmt=null;
        ResultSet rs = null;
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/store";
            Connection conn = (Connection) DriverManager.getConnection(database, "root", "tiger");
            stmt = (Statement) conn.createStatement();
            String sql = "select * from user where name = '" + ID + "'";
            rs = stmt.executeQuery(sql);
            rs.next();
            str = rs.getString("pass");
            icon = rs.getInt("icon");
            rs.close();
            stmt.close();
            conn.close();
            if(str.equals(PWord)) {
               Menu m = new Menu();
                m.setVisible(true);
                this.setVisible(false);
                m.jLabel6.setText("" + ID);
                switch(icon)
                {case 1 :
                     m.jLabel1.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\PROFILE PICS\\i1 - Copy (2).png"));
                     break;
                 case 2 :
                     m.jLabel1.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\PROFILE PICS\\i2 - Copy (2).png"));
                     break;
                 case 3 :
                     m.jLabel1.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\PROFILE PICS\\i3 - Copy (2).png"));
                     break;
                 case 4 :
                     m.jLabel1.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\PROFILE PICS\\i4 - Copy (2).png"));
                     break;
                  case 5 :
                     m.jLabel1.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\PROFILE PICS\\i5 - Copy (2).png"));
                     break;
                  case 6 :
                     m.jLabel1.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\PROFILE PICS\\i6 - Copy (2).png"));
                     break;
                  case 7 :
                     m.jLabel1.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\PROFILE PICS\\i7 - Copy (2).png"));
                     break;
                  case 8 :
                     m.jLabel1.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\PROFILE PICS\\i8 - Copy (2).png"));
                     break;
                  case 9 :
                     m.jLabel1.setIcon(new javax.swing.ImageIcon("M:\\IP PROJECT 2018-19\\PICTURES\\PROFILE PICS\\i9 - Copy (2).png"));
                     break;
                }
            } else {
                invalid.setText(" * Incorrect ID or Password !");
            }
        } catch (Exception e) { invalid.setText(" * Incorrect ID or Password");}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        String er = new String(PassWordPF.getPassword());
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/store","root","tiger");
            stemt = con.createStatement();
            String query = "select * from user where name = '"+idtf.getText()+"';";
            rs = stemt.executeQuery(query);
            if(rs.next()) {
                String un = rs.getString("name");
                String pw = rs.getString("pass");
                String in = rs.getString("icon");
                int result = Integer.parseInt(in);
                if(er.equals(pw)== true) {
                    JOptionPane.showMessageDialog(null,"Hello " + un +".");
                    new Menu().setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null,"Password is wrong");
                }
            } else {
                JOptionPane.showMessageDialog(null,"No Record Found");
            }
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error in Connectivity");
        }
        String y =  new String(PassWordPF.getPassword());
        int b = y.length();

        if (b==0) {
            jLabel13.setText("");
            PassWordPF.setEchoChar((char)0);
            //System.out.println("y es its null");
            PassWordPF.setText("PASSWORD");
            PassWordPF.setForeground(new java.awt.Color(102, 102, 102));
            jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        } else {
            //System.out.println("n o its not null");
            //System.out.println(""+y);
            PassWordPF.setText(""+y);
            jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        }
        String x = idtf.getText();
        int c = x.length();

        if (c==0) {
            idtf.setForeground(new java.awt.Color(102,102,102));
            //System.out.println("y es its null");
            idtf.setText("USERNAME");
            jLabel10.setText("");
            jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        } else {
            //System.out.println("n o its not null");
            //System.out.println(""+x);
            idtf.setText(""+x);
            jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        }
}//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setState(ICONIFIED);
}//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
}//GEN-LAST:event_jLabel6MouseClicked

    private void idtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtfActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_idtfActionPerformed

    private void idtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idtfFocusGained
        // TODO add your handling code here:
        jLabel10.setText(""+"USERNAME");
        idtf.setText("");
        idtf.setForeground(new java.awt.Color(0, 0,0));
        jLabel9.setBackground(new java.awt.Color(11,198,160));
}//GEN-LAST:event_idtfFocusGained

    private void idtfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idtfFocusLost
        // TODO add your handling code here:
        String x = idtf.getText();
        int a = x.length();

        if (a==0) {
            idtf.setForeground(new java.awt.Color(102,102,102));
            //System.out.println("y es its null");
            idtf.setText("USERNAME");
            jLabel10.setText("");
            jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        } else {
            //System.out.println("n o its not null");
            //System.out.println(""+x);
            idtf.setText(""+x);
            jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        }
}//GEN-LAST:event_idtfFocusLost

    private void PassWordPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassWordPFActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_PassWordPFActionPerformed

    private void PassWordPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassWordPFFocusGained
        // TODO add your handling code here:
        jLabel15.setVisible(false);
        jLabel14.setVisible(true);
        PassWordPF.setEchoChar('•');
        jLabel13.setText(""+"PASSWORD");
        PassWordPF.setText("");
        PassWordPF.setForeground(new java.awt.Color(0, 0,0));
        jLabel12.setBackground(new java.awt.Color(11,198,160));
}//GEN-LAST:event_PassWordPFFocusGained

    private void PassWordPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassWordPFFocusLost
        // TODO add your handling code here:
        String y =  new String(PassWordPF.getPassword());
        int a = y.length();

        if (a==0) {
            jLabel13.setText("");
            PassWordPF.setEchoChar((char)0);
            //System.out.println("y es its null");
            PassWordPF.setText("PASSWORD");
            PassWordPF.setForeground(new java.awt.Color(102, 102, 102));
            jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        } else {
            //System.out.println("n o its not null");
            //System.out.println(""+y);
            PassWordPF.setText(""+y);
            jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        }
}//GEN-LAST:event_PassWordPFFocusLost

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        //show password
        jLabel15.setVisible(true);
        jLabel15.setLocation(420, 250);
        jLabel14.setVisible(false);
        PassWordPF.setEchoChar((char)0);
}//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        //hide password
        jLabel15.setVisible(false);
        jLabel14.setVisible(true);
        jLabel14.setLocation(420, 250);
        PassWordPF.setEchoChar('•');
}//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        new Signup().setVisible(true);
}//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
PassWordPF.setEchoChar((char)0);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       jLabel6.setIcon(new javax.swing.ImageIcon("D:\\IP PROJECT 2018-19\\PICTURES\\CLOSE.png"));
       jLabel7.setIcon(new javax.swing.ImageIcon("D:\\IP PROJECT 2018-19\\PICTURES\\MINIMISE.png"));
        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\IP PROJECT 2018-19\\PICTURES\\SHOW PASSWORD.png"));
       jLabel15.setIcon(new javax.swing.ImageIcon("D:\\IP PROJECT 2018-19\\PICTURES\\HIDE PASSWORD.png"));
    }//GEN-LAST:event_formWindowOpened

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PassWordPF;
    private javax.swing.JTextField idtf;
    private javax.swing.JLabel invalid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
